bbcWeatherEndpoints:
  observationsEndpoint: https://weather-broker-cdn.api.bbci.co.uk/en/observation/
  locationEndpoint: https://weather-broker-cdn.api.bbci.co.uk/locator/en/locations/

views:
  freemarker:
    strict_syntax: yes
    whitespace_stripping: yes